---
# Collections from Ansible Galaxy
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: ansible.utils
    version: ">=2.0.0"
  
  - name: community.general
    version: ">=7.0.0"
    # parted, ufw, systemd, sysctl, timezone, etc.
  
  - name: community.crypto
    version: ">=2.0.0"
    # cryptography modules, certificate management, etc.
  
  - name: community.network
    version: ">=5.0.0"
roles:
  - name: dev-sec.os-hardening
    version: "7.0.0"
