all:
  hosts:
    server1:
      ansible_host: 192.168.64.2
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws-test-user
      # Partition to encrypt (adjust as needed)
      encrypt_partition: /dev/sdb1
      # Alternative: specify entire disk if no partitions exist
      # encrypt_disk: /dev/sdb
  vars:
    ansible_python_interpreter: /usr/bin/python3
    bootstrap_reboot_timeout: 600
    bootstrap_wait_for_connection: 30
